#%RAML 1.0 NamedExample
productexample:
value:
  -
    ProductId: P1
    ProductName: Product1
    ProductDesc: Dummy product
    UnitPrice: 345.23
    AvailableUnits: 20

  -
    ProductId: P2
    ProductName: Product2
    ProductDesc: Dummy product 2
    UnitPrice: 3345.23
    AvailableUnits: 200

  -
    ProductId: P3
    ProductName: Product3
    ProductDesc: Dummy product 3
    UnitPrice: 76345.23
    AvailableUnits: 2