#%RAML 1.0 DataType
type: object
properties:
  ProductId:
    example: P1
    type: string
  ProductName:
    example: Product1
    type: string 
  ProductDesc:
    example: Dummy product
    type: string
  UnitPrice:
    example: 345.23
    type: number
  AvailableUnits:
    example: 200
    type: integer
  